# Generated by Django 4.0.2 on 2023-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_album_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='article',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
