# Generated by Django 4.0.2 on 2023-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='piece',
            field=models.CharField(choices=[('C', 'Classic'), ('O', 'Okay '), ('B', 'Bad')], default='C', max_length=1),
        ),
    ]
