# Generated by Django 4.0.2 on 2023-08-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_review_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='article',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(verbose_name='Reading Date'),
        ),
    ]
