# Generated by Django 4.0.2 on 2023-08-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_format_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='formats',
            field=models.ManyToManyField(to='main_app.Format'),
        ),
    ]
